MODEL:
  META_ARCHITECTURE: "NLOSDetector"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  NLOS_CONVERTER:
    NAME: "conv_fc_nlos_converter"
    NUM_CONVS: 3
    INT_CONV_CHANNEL: 32
    IN_FC_CHANNELS:  [16 , 4] #[4 * 16 * 256 2 * 8 * 256, 1 * 4 * 256]
    #IN_FC_CHANNELS:  [ 60 , 16] #INPUT 128
    #IN_FC_CHANNELS:  [ 240 , 60] #INPUT 256
    #OUT_FC_CHANNELS: [30 * 40 , 15 * 20 * 256, 8 * 10 * 256]
    OUT_FC_CHANNELS: [[15,20],[8,10]]
    IN_FEATURES: ["p5", "p6"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    IN_FEATURES: ["p5", "p6"]
    FPN_STRIDES: [32, 64]
    NUM_CLASSES: 2
    SIZES_OF_INTEREST: [128]
    INFERENCE_TH_TEST: 0.5
  PIXEL_MEAN: [ 2.8969,  3.9573, 11.9117]
  PIXEL_STD: [0.7269, 1.5346, 5.0199]
DATASETS:
  TRAIN: ("nlos_2020_train",)
  TEST: ("nlos_2020_valid",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (40000, 50000)
  MAX_ITER: 60000
INPUT:
  NLOS: True
  MIN_SIZE_TRAIN: (64,)
  MIN_SIZE_TEST: 64
  HFLIP_TRAIN: False
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 80
