_BASE_: "Base-NLOS.yaml"
MODEL:
  NLOS_CONVERTER:
    NAME: "channel_preserving_nlos_converter"
    INT_CONV_CHANNEL: 256
    IN_FC_CHANNELS:  [16 , 4] #[4 * 16 * 256 2 * 8 * 256, 1 * 4 * 256]
    OUT_FC_CHANNELS: [[15,20],[8,10]]
    IN_FEATURES: ["p5", "p6"]
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 8

